### ISSUE TITLE
"plugin_sketchcanvas" is NOT an array! - please update the plugin

### ISSUE THREAD

**Issue by Floffyko** [msakuta/SketchCanvas#4]
Could you please update the plugin?
The following error have to be solved. Thanks you.

`startSectionEdit: $data "plugin_sketchcanvas" is NOT an array! One of your plugins needs an update.`

**Comment by msakuta** [comment]
Can you tell me which version of DokuWiki you have the error?  I'm sorry that I've been lazy enough to test on newest releases.

**Comment by Floffyko** [comment]
Hi, it is about the version Greebo. I was somehow "forced" to update on my second server. It is nothing wrong with your plugin, it is just a "litle" mod Andreas and his team made to DW. Thereafter almost all the plugins have to update a few lines. 
See  
/cosmocode/dokuwiki-plugin-tabbox/pull/6
/cosmocode/dokuwiki-plugin-tabbox/issues/5

nice approach, by the way :)
